# Generated by Django 5.2.10 on 2026-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='products', through='orders.OrderedProduct', to='orders.order'),
        ),
    ]
