# Generated by Django 5.2.10 on 2026-02-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_supplier'),
        ('orders', '0002_orderedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='products', through='orders.OrderedProduct', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='inventory.category'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
