# Generated by Django 5.2.10 on 2026-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=120, blank=True),
        ),
    ]
